//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkGeo.MapSuite.SiteSelection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThinkGeo.MapSuite.SiteSelection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Maps Aerial.
        /// </summary>
        internal static string BingMapsAerialOverlayName {
            get {
                return ResourceManager.GetString("BingMapsAerialOverlayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Maps Road.
        /// </summary>
        internal static string BingMapsRoadOverlayName {
            get {
                return ResourceManager.GetString("BingMapsRoadOverlayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom.
        /// </summary>
        internal static string CustomOverlayKey {
            get {
                return ResourceManager.GetString("CustomOverlayKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string DistanceKey {
            get {
                return ResourceManager.GetString("DistanceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistanceUnit.
        /// </summary>
        internal static string DistanceUnitKey {
            get {
                return ResourceManager.GetString("DistanceUnitKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveTime.
        /// </summary>
        internal static string DriveTimeInMinutesKey {
            get {
                return ResourceManager.GetString("DriveTimeInMinutesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighlightFeatureLayer.
        /// </summary>
        internal static string HighlightFeatureLayerKey {
            get {
                return ResourceManager.GetString("HighlightFeatureLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels.
        /// </summary>
        internal static string HotelsLayerKey {
            get {
                return ResourceManager.GetString("HotelsLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marker.
        /// </summary>
        internal static string MakerOverlayKey {
            get {
                return ResourceManager.GetString("MakerOverlayKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Facilites.
        /// </summary>
        internal static string MedicalFacilitesLayerKey {
            get {
                return ResourceManager.GetString("MedicalFacilitesLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Street Map.
        /// </summary>
        internal static string OSMOverlayName {
            get {
                return ResourceManager.GetString("OSMOverlayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poi.
        /// </summary>
        internal static string PoiOverlayKey {
            get {
                return ResourceManager.GetString("PoiOverlayKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Facilites.
        /// </summary>
        internal static string PublicFacilitesLayerKey {
            get {
                return ResourceManager.GetString("PublicFacilitesLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        internal static string RestaurantsLayerKey {
            get {
                return ResourceManager.GetString("RestaurantsLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restricted.
        /// </summary>
        internal static string RestrictedLayerKey {
            get {
                return ResourceManager.GetString("RestrictedLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScaleBar.
        /// </summary>
        internal static string ScaleBarLayerKey {
            get {
                return ResourceManager.GetString("ScaleBarLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools.
        /// </summary>
        internal static string SchoolsLayerKey {
            get {
                return ResourceManager.GetString("SchoolsLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serviceArea.
        /// </summary>
        internal static string ServiceAreaLayerKey {
            get {
                return ResourceManager.GetString("ServiceAreaLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PathFilename.
        /// </summary>
        internal static string StreetShapePathFilenameKey {
            get {
                return ResourceManager.GetString("StreetShapePathFilenameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkGeo Cloud Aerial.
        /// </summary>
        internal static string ThinkGeoCloudAerialMap {
            get {
                return ResourceManager.GetString("ThinkGeoCloudAerialMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkGeo Cloud Hybrid.
        /// </summary>
        internal static string ThinkGeoCloudHybrid {
            get {
                return ResourceManager.GetString("ThinkGeoCloudHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkGeo Cloud Light .
        /// </summary>
        internal static string ThinkGeoCloudLightMap {
            get {
                return ResourceManager.GetString("ThinkGeoCloudLightMap", resourceCulture);
            }
        }
    }
}
