//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkGeo.MapSuite.EarthquakeStatistics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThinkGeo.MapSuite.EarthquakeStatistics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BingAerial.
        /// </summary>
        internal static string BingMapsAerial {
            get {
                return ResourceManager.GetString("BingMapsAerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Maps Aerial.
        /// </summary>
        internal static string BingMapsAerialOverlayName {
            get {
                return ResourceManager.GetString("BingMapsAerialOverlayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BingRoad.
        /// </summary>
        internal static string BingMapsRoad {
            get {
                return ResourceManager.GetString("BingMapsRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Maps Road.
        /// </summary>
        internal static string BingMapsRoadOverlayName {
            get {
                return ResourceManager.GetString("BingMapsRoadOverlayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_hand {
            get {
                object obj = ResourceManager.GetObject("cursor_hand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPTH_KM.
        /// </summary>
        internal static string DepthColumnName {
            get {
                return ResourceManager.GetString("DepthColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap draw_circle {
            get {
                object obj = ResourceManager.GetObject("draw_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap draw_polygon {
            get {
                object obj = ResourceManager.GetObject("draw_polygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Draw_Rectangle {
            get {
                object obj = ResourceManager.GetObject("Draw_Rectangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expand {
            get {
                object obj = ResourceManager.GetObject("expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heatMap {
            get {
                object obj = ResourceManager.GetObject("heatMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Map.
        /// </summary>
        internal static string HeatStyleLayerName {
            get {
                return ResourceManager.GetString("HeatStyleLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IsoLine {
            get {
                object obj = ResourceManager.GetObject("IsoLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsolineLevelLegendLayer.
        /// </summary>
        internal static string IsoLineLevelLegendLayerName {
            get {
                return ResourceManager.GetString("IsoLineLevelLegendLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsoLines Map.
        /// </summary>
        internal static string IsolineStyleLayerName {
            get {
                return ResourceManager.GetString("IsolineStyleLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LATITIUDE.
        /// </summary>
        internal static string LatitudeColumnName {
            get {
                return ResourceManager.GetString("LatitudeColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCATION.
        /// </summary>
        internal static string LocationColumnName {
            get {
                return ResourceManager.GetString("LocationColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LONGITUDE.
        /// </summary>
        internal static string LongitudeColumnName {
            get {
                return ResourceManager.GetString("LongitudeColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAGNITUDE.
        /// </summary>
        internal static string MagnitudeColumnName {
            get {
                return ResourceManager.GetString("MagnitudeColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MapSuite {
            get {
                object obj = ResourceManager.GetObject("MapSuite", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenStreetMap.
        /// </summary>
        internal static string OpenStreetMapKey {
            get {
                return ResourceManager.GetString("OpenStreetMapKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Street Map.
        /// </summary>
        internal static string OSMOverlayName {
            get {
                return ResourceManager.GetString("OSMOverlayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pan {
            get {
                object obj = ResourceManager.GetObject("Pan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pointMap {
            get {
                object obj = ResourceManager.GetObject("pointMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Point Map.
        /// </summary>
        internal static string PointStyleLayerName {
            get {
                return ResourceManager.GetString("PointStyleLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleLayerOverLay.
        /// </summary>
        internal static string StyleLayerOverLayKey {
            get {
                return ResourceManager.GetString("StyleLayerOverLayKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap switcher_maxmize {
            get {
                object obj = ResourceManager.GetObject("switcher_maxmize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap switcher_minimize {
            get {
                object obj = ResourceManager.GetObject("switcher_minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thinkgeo_logo_small {
            get {
                object obj = ResourceManager.GetObject("thinkgeo_logo_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkGeo Cloud Maps Aerial.
        /// </summary>
        internal static string ThinkGeoCloudMapsOverlayAerial {
            get {
                return ResourceManager.GetString("ThinkGeoCloudMapsOverlayAerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkGeo Cloud Maps Hybrid.
        /// </summary>
        internal static string ThinkGeoCloudMapsOverlayHybrid {
            get {
                return ResourceManager.GetString("ThinkGeoCloudMapsOverlayHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkGeo Cloud Maps Light.
        /// </summary>
        internal static string ThinkGeoCloudMapsOverlayLight {
            get {
                return ResourceManager.GetString("ThinkGeoCloudMapsOverlayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string UnknownString {
            get {
                return ResourceManager.GetString("UnknownString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Map Kit.
        /// </summary>
        internal static string WorldMapKitOverlayName {
            get {
                return ResourceManager.GetString("WorldMapKitOverlayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEAR.
        /// </summary>
        internal static string YearColumnName {
            get {
                return ResourceManager.GetString("YearColumnName", resourceCulture);
            }
        }
    }
}
