//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkGeo.MapSuite.SiteSelection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThinkGeo.MapSuite.SiteSelection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Maps Aerial.
        /// </summary>
        internal static string BingMapsAerialOverlayName {
            get {
                return ResourceManager.GetString("BingMapsAerialOverlayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Maps Road.
        /// </summary>
        internal static string BingMapsRoadOverlayName {
            get {
                return ResourceManager.GetString("BingMapsRoadOverlayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cursor_hand {
            get {
                object obj = ResourceManager.GetObject("cursor_hand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom.
        /// </summary>
        internal static string CustomOverlayKey {
            get {
                return ResourceManager.GetString("CustomOverlayKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string DistanceKey {
            get {
                return ResourceManager.GetString("DistanceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistanceUnit.
        /// </summary>
        internal static string DistanceUnitKey {
            get {
                return ResourceManager.GetString("DistanceUnitKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap drawPoint {
            get {
                object obj = ResourceManager.GetObject("drawPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveTimeInMinutes.
        /// </summary>
        internal static string DriveTimeInMinutesKey {
            get {
                return ResourceManager.GetString("DriveTimeInMinutesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DrugStore {
            get {
                object obj = ResourceManager.GetObject("DrugStore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expand {
            get {
                object obj = ResourceManager.GetObject("expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string FindAllText {
            get {
                return ResourceManager.GetString("FindAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeographyUnit.
        /// </summary>
        internal static string GeographyUnitKey {
            get {
                return ResourceManager.GetString("GeographyUnitKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighlightFeatureLayer.
        /// </summary>
        internal static string HighlightFeatureLayerKey {
            get {
                return ResourceManager.GetString("HighlightFeatureLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hotel {
            get {
                object obj = ResourceManager.GetObject("Hotel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels.
        /// </summary>
        internal static string HotelsLayerKey {
            get {
                return ResourceManager.GetString("HotelsLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string MainForm_MainForm_Load__2 {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load__2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string MainForm_MainForm_Load__6 {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load__6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marker.
        /// </summary>
        internal static string MakerOverlayKey {
            get {
                return ResourceManager.GetString("MakerOverlayKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MapSuite {
            get {
                object obj = ResourceManager.GetObject("MapSuite", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Facilites.
        /// </summary>
        internal static string MedicalFacilitesLayerKey {
            get {
                return ResourceManager.GetString("MedicalFacilitesLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        internal static string NoResultText {
            get {
                return ResourceManager.GetString("NoResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Street Map.
        /// </summary>
        internal static string OSMOverlayName {
            get {
                return ResourceManager.GetString("OSMOverlayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pan {
            get {
                object obj = ResourceManager.GetObject("pan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poi.
        /// </summary>
        internal static string PoiOverlayKey {
            get {
                return ResourceManager.GetString("PoiOverlayKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap public_facility {
            get {
                object obj = ResourceManager.GetObject("public_facility", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Facilites.
        /// </summary>
        internal static string PublicFacilitesLayerKey {
            get {
                return ResourceManager.GetString("PublicFacilitesLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap restaurant {
            get {
                object obj = ResourceManager.GetObject("restaurant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        internal static string RestaurantsLayerKey {
            get {
                return ResourceManager.GetString("RestaurantsLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restricted.
        /// </summary>
        internal static string RestrictionLayerKey {
            get {
                return ResourceManager.GetString("RestrictionLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScaleBar.
        /// </summary>
        internal static string ScaleBarLayerKey {
            get {
                return ResourceManager.GetString("ScaleBarLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap school {
            get {
                object obj = ResourceManager.GetObject("school", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools.
        /// </summary>
        internal static string SchoolsLayerKey {
            get {
                return ResourceManager.GetString("SchoolsLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that this sample map is only able to analyze service areas within the Frisco, TX city limits, which are indicated by a dashed red line.  Click inside that boundary for best results..
        /// </summary>
        internal static string SearchOutOfBoundaryMessage {
            get {
                return ResourceManager.GetString("SearchOutOfBoundaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap selectedHalo {
            get {
                object obj = ResourceManager.GetObject("selectedHalo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serviceArea.
        /// </summary>
        internal static string ServiceAreaLayerKey {
            get {
                return ResourceManager.GetString("ServiceAreaLayerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetShapePathFilename.
        /// </summary>
        internal static string StreetShapePathFilenameKey {
            get {
                return ResourceManager.GetString("StreetShapePathFilenameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap switcher_maxmize {
            get {
                object obj = ResourceManager.GetObject("switcher_maxmize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap switcher_minimize {
            get {
                object obj = ResourceManager.GetObject("switcher_minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thinkgeo_logo_small {
            get {
                object obj = ResourceManager.GetObject("thinkgeo_logo_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkGeo Cloud Maps Aerial.
        /// </summary>
        internal static string ThinkGeoCloudMapsOverlayAerial {
            get {
                return ResourceManager.GetString("ThinkGeoCloudMapsOverlayAerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkGeo Cloud Maps Hybrid.
        /// </summary>
        internal static string ThinkGeoCloudMapsOverlayHybrid {
            get {
                return ResourceManager.GetString("ThinkGeoCloudMapsOverlayHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThinkGeo Cloud Maps Light.
        /// </summary>
        internal static string ThinkGeoCloudMapsOverlayLight {
            get {
                return ResourceManager.GetString("ThinkGeoCloudMapsOverlayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
    }
}
